import { skillsItemType } from "../app.types";

export const skillsData: skillsItemType[] = [
  { label: 'Angular', type: 'Languages', rating: 10, years: 7  },
  { label: 'React', type: 'Languages', rating: 7 , years: 4 },
  { label: 'AngularJS', type: 'Languages', rating: 6 , years: 3 },
  { label: 'NodeJS', type: 'Languages', rating: 7 , years: 5 },
  { label: 'Javascript', type: 'Languages', rating: 8 , years: 10 },
  { label: 'Typescript', type: 'Languages', rating: 10 , years: 7 },
  { label: 'HTML', type: 'Languages', rating: 8 , years: 10 },
  { label: 'CSS / SCSS / SASS', type: 'Languages', rating: 8 , years: 10 },
  { label: 'REST APIS', type: 'Integrations', rating: 9 , years: 10 },
  { label: 'GraphQL APIS', type: 'Integrations', rating: 6 , years: 4 },
  { label: 'Sockets / PubNub', type: 'Integrations', rating: 8 , years: 4 },
  { label: 'D3', type: 'Integrations', rating: 6 , years: 5 },
  { label: 'ChartJs', type: 'Integrations', rating: 8 , years: 4 },
  { label: 'Kendo / Highcharts', type: 'Integrations', rating: 5 , years: 3 },
  { label: 'SSO (Okta/Google)', type: 'Integrations', rating: 6 , years: 2 },
  { label: 'Mapbox / Google Maps', type: 'Integrations', rating: 6 , years: 5 },
  { label: 'AWS web services', type: 'Integrations', rating: 7 , years: 7 },
  { label: 'Google web services', type: 'Integrations', rating: 5 , years: 3 },
  { label: 'Software Architecture', type: 'Development', rating: 10 , years: 10 },
  { label: 'Interface Design', type: 'Development', rating: 8 , years: 10 },
  { label: 'Graphic Design', type: 'Development', rating: 7 , years: 5 },
  { label: 'Product Design', type: 'Development', rating: 5 , years: 4 },
  { label: 'Hiring / Interviewing', type: 'Development', rating: 10 , years: 6 },
  { label: 'Asset Management', type: 'Development', rating: 9 , years: 3 },
  { label: 'Testing / QA', type: 'Development', rating: 6 , years: 3 },
  { label: 'Standards and Protocols', type: 'Development', rating: 9 , years: 10 },
  { label: 'Github / Jira', type: 'Tools', rating: 9 , years: 8 },
  { label: 'Heroku', type: 'Tools', rating: 7 , years: 2 },
  { label: 'Figma', type: 'Tools', rating: 6 , years: 3 },
  { label: 'Curl / Postman', type: 'Tools', rating: 8 , years: 10 },
  { label: 'Google Suite', type: 'Tools', rating: 5 , years: 8 },
] || null;

