import { skillsItemType } from "../app.types";

export const skillsData: skillsItemType[] = [
  { label: 'Angular', type: 'Languages', rating: 10 },
  { label: 'React', type: 'Languages', rating: 7 },
  { label: 'AngularJS', type: 'Languages', rating: 6 },
  { label: 'NodeJS', type: 'Languages', rating: 7 },
  { label: 'Javascript', type: 'Languages', rating: 8 },
  { label: 'Typescript', type: 'Languages', rating: 10 },
  { label: 'HTML', type: 'Languages', rating: 8 },
  { label: 'CSS/SCSS/SASS', type: 'Languages', rating: 8 },
  { label: 'REST APIS', type: 'Integrations', rating: 9 },
  { label: 'GraphQL APIS', type: 'Integrations', rating: 7 },
  { label: 'D3', type: 'Integrations', rating: 6 },
  { label: 'ChartJs', type: 'Integrations', rating: 8 },
  { label: 'Kendo / Highcharts', type: 'Integrations', rating: 5 },
  { label: 'SSO (Okta/Google)', type: 'Integrations', rating: 6 },
  { label: 'Mapbox/Google Maps', type: 'Integrations', rating: 6 },
  { label: 'AWS web services', type: 'Integrations', rating: 7 },
  { label: 'Google web services', type: 'Integrations', rating: 5 },
  { label: 'Software Architecture', type: 'Skills', rating: 10 },
  { label: 'Interface Design', type: 'Skills', rating: 8 },
  { label: 'Graphic Design', type: 'Skills', rating: 6 },
  { label: 'Product Design', type: 'Skills', rating: 8 },
  { label: 'SW Deployment', type: 'Skills', rating: 7 },
  { label: 'Asset Management', type: 'Skills', rating: 9 },
  { label: 'Testing / QA', type: 'Skills', rating: 6 },
  { label: 'Standards and protocols', type: 'Skills', rating: 9 },
  { label: 'Github', type: 'Tools', rating: 7 },
  { label: 'JIRA', type: 'Tools', rating: 8 },
  { label: 'Heroku', type: 'Tools', rating: 7 },
  { label: 'Figma', type: 'Tools', rating: 5 },
  { label: 'Curl / Postman', type: 'Tools', rating: 7 },
  { label: 'Requestly', type: 'Tools', rating: 9 },
  { label: 'Adobe', type: 'Tools', rating: 7 },
  { label: 'Google Suite', type: 'Tools', rating: 7 },

] || null;

